name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./SpondyCalculator
        
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      #if: github.event_name == 'workflow_dispatch' # Only publish if Workflow manually ran
      with:
        name: app
        path: ./SpondyCalculator/build/
      
  deploy:
    needs: build 
    
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [16.x]
    
    name: Deploy
    #if: github.event_name == 'workflow_dispatch' # Only deploy if Workflow manually ran
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: app
        path: dist
        
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
